package jp.pinkikki.domain.hero.model;

public class EventDetail extends EventDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_detail.attr1
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    private String attr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_detail.attr2
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    private String attr2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_detail.attr1
     *
     * @return the value of event_detail.attr1
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_detail.attr1
     *
     * @param attr1 the value for event_detail.attr1
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public void setAttr1(String attr1) {
        this.attr1 = attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_detail.attr2
     *
     * @return the value of event_detail.attr2
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public String getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_detail.attr2
     *
     * @param attr2 the value for event_detail.attr2
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public void setAttr2(String attr2) {
        this.attr2 = attr2;
    }
}