package jp.pinkikki.domain.hero.model;

public class Event {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_id
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    private Integer eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.object_name
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    private String objectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.procedure
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    private Integer procedure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.scene_name
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    private String sceneName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_id
     *
     * @return the value of event.event_id
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_id
     *
     * @param eventId the value for event.event_id
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.object_name
     *
     * @return the value of event.object_name
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.object_name
     *
     * @param objectName the value for event.object_name
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public void setObjectName(String objectName) {
        this.objectName = objectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.procedure
     *
     * @return the value of event.procedure
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public Integer getProcedure() {
        return procedure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.procedure
     *
     * @param procedure the value for event.procedure
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public void setProcedure(Integer procedure) {
        this.procedure = procedure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.scene_name
     *
     * @return the value of event.scene_name
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public String getSceneName() {
        return sceneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.scene_name
     *
     * @param sceneName the value for event.scene_name
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public void setSceneName(String sceneName) {
        this.sceneName = sceneName;
    }
}