package jp.pinkikki.domain.hero.model;

public class EventDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_detail.event_id
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    private Integer eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_detail.seq
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_detail.type_id
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    private Integer typeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_detail.event_id
     *
     * @return the value of event_detail.event_id
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_detail.event_id
     *
     * @param eventId the value for event_detail.event_id
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_detail.seq
     *
     * @return the value of event_detail.seq
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_detail.seq
     *
     * @param seq the value for event_detail.seq
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_detail.type_id
     *
     * @return the value of event_detail.type_id
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_detail.type_id
     *
     * @param typeId the value for event_detail.type_id
     *
     * @mbg.generated Mon Jan 29 20:45:33 JST 2018
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
}